---
title: "samecolorsbetweenplots"
output: html_document
---

#load packages
```{r}
library(ampvis2)
library(tidyverse)
```

#subset data
```{r}
#subset to PAOs according to MiF
aalborgwwtps_PAOs <- amp_subset_taxa(AalborgWWTPs, paste0("g__", filter(MiF, PAO %in% "POS")$Genus), normalise = TRUE)
#or grepl to be search by substring
#PAOs <- AalborgWWTPs$tax$Genus[which(stringr::str_detect(AalborgWWTPs$tax$Genus, filter(MiF, PAO %in% "POS")$Genus))]
#aalborgwwtps_PAOs <- amp_subset_taxa(AalborgWWTPs, PAOs)

AAW <- amp_subset_samples(aalborgwwtps_PAOs, Plant %in% "Aalborg West")
AAE <- amp_subset_samples(aalborgwwtps_PAOs, Plant %in% "Aalborg East")
```

#plots
```{r}
AAWts <- amp_timeseries(AAW, 
                        time_variable = "Date",
                        tax_aggregate = "Genus",
                        tax_add = "Phylum",
                        tax_show = 5,
                        normalise = FALSE)
savefactorfromfirstplot <- AAWts$data$Genus #reorder this if you want different colors for each
AAWts + scale_color_discrete(drop = FALSE,
                             limits = levels(savefactorfromfirstplot),
                             breaks = unique(savefactorfromfirstplot))
amp_timeseries(AAE,
               time_variable = "Date",
               tax_aggregate = "Genus",
               tax_add = "Phylum",
               tax_show = 5,
               normalise = FALSE) + 
  scale_color_discrete(drop = FALSE,
                       limits = levels(savefactorfromfirstplot),
                       breaks = unique(savefactorfromfirstplot))
```
